[package]
name = "ruspiro-uart"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.0.3" # remember to update html_root_url
description = "This crate provides a convinient access API to the Raspberry Pi 3 UART interface"
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-uart/tree/v0.0.3"
documentation = "https://docs.rs/ruspiro-uart/0.0.3"
readme = "README.md"
keywords = ["RusPiRo", "uart", "baremetal", "raspberrypi"]
categories = ["no-std", "embedded"]
edition = "2018"

[lib]

[dependencies]
ruspiro-gpio = "0.0.2"
ruspiro-register = "0.0.2"
ruspiro-console = "0.0.2"

[features]
