[package]
name = "ruspiro-uart"
authors = ["André Borrmann <pspwizard@gmx.de>"]
version = "0.2.0" # remember to update html_root_url
description = """
Simple and convinient access API to the Raspberry Pi 3 UART0 (PL011) and UART1 (miniUART) interface
"""
license = "Apache-2.0"
repository = "https://github.com/RusPiRo/ruspiro-uart"
documentation = "https://docs.rs/ruspiro-uart/0.2.0"
readme = "README.md"
keywords = ["RusPiRo", "uart", "baremetal", "raspberrypi"]
categories = ["no-std", "embedded"]
edition = "2018"

[badges]
travis-ci = { repository = "RusPiRo/ruspiro-uart", branch = "master" }
maintenance = { status = "actively-developed" }


[lib]

[dependencies]
ruspiro-gpio = "0.2"
ruspiro-register = "0.1"
ruspiro-timer = "0.1"
ruspiro-console = "0.2"

[features]
default = ["ruspiro_pi3"]
ruspiro_pi3 = []